### ISSUE TITLE
mkdir build - Problem and workaround on Windows 10

### ISSUE THREAD

**Issue by makingsoundmachines** [electro-smith/DaisyWiki#10]
Hey everyone,

following the Getting Started tutorial [1.-Setting-Up-Your-Development-Environment](https://github.com/electro-smith/DaisyWiki/wiki/1.-Setting-Up-Your-Development-Environment) and specifically [for Windows 10](https://github.com/electro-smith/DaisyWiki/wiki/1c.-Installing-the-Toolchain-on-Windows) we ran into a weird problem with make.

Following the tutorial and just running `make` from a directory with an example, e.g. [ADenv](https://github.com/electro-smith/DaisySP/tree/master/examples/adenv) exits and fails with the following line:

```
mkdir build
process_begin: CreateProcess(NULL, mkdir build, ...) failed.
```
This problem is present both in the Windows Command Line (cmd, the black one) and PowerShell (the blue one).

The **workaround** is to create the directory called **build** manually in the file explorer.  Make then compiles the files as intended, even though the failure prompt remains present (but gets skipped over).

I suspect the mkdir command is not available by default in windows, and there may be a way to enable it. This might be worth a note in the getting started tutorial (certainly caused some headscratching here before we figured it out.)

**Comment by andrewikenberry** [comment]
Did you try using [Git Bash?](https://gitforwindows.org/)

**Comment by makingsoundmachines** [comment]
@andrewikenberry thank you Andrew, I just tried Git Bash and it does indeed work there.

However you can't easily copy paths e.g. the example directory into git bash because git bash expects / as indicator for folders instead of \ (what you would get if you copy a local path in Windows). So creating the folder manually is a lot quicker that search and replace the backslashes ..

The ideal way would be to somehow enable the command `mkdir` in the Windows shell.

**Comment by andrewikenberry** [comment]
FWIW you can drag folders into Git Bash and it will automatically use /

I will get some notes about these things in the Wiki.

**Comment by makingsoundmachines** [comment]
hmm here it copies the path "as usual" when I drag and drop into Git Bash. Don't know why that's different on my PC but drag and drop paths show like this `D:\code\daisy\toolchain\DaisySP\examples\whitenoise` 

Don't worry though I can live with the workaround .. note in the Wiki would be great though.

**Comment by h2g2guy** [comment]
This is a rather late comment, and I'm not sure whether it'll be terribly helpful -- but I've been using Windows Subsystem for Linux and it just seems to me to be a better overall experience for embedded development on Windows. No need to deal with the finickiness of Git Bash or inconsistent path separators or installers messing with your system.

This of course assumes that you have experience with, or are willing to learn, a Linux distro. But I figured I'd toss it out there, since it seemed to me to be a better option for both Daisy development _**and**_ development of oscillators for Korg's 'logue synths.

**Comment by stephenhensley** [comment]
I think the version of Make we bundle with the "DaisyToolchain" now works for both command prompt, and git-bash, etc.

That said, I also added a note in the "More Setup (Windows)" section of the guide that mentions this issue in case anyone runs into it.
