### ISSUE TITLE
Provide (better) instructions for installing openocd on all OSes

### ISSUE THREAD

**Issue by stephenhensley** [electro-smith/DaisyWiki#12]
At present, the only instructions for installing openocd are in the MacOS section, and recommend building from source

Recently, the forum had brought up the xpack distribution of openocd which I have tested on windows so far and it works with the STM32H750.

Installation instructions are here:
https://xpack.github.io/openocd/install/

It'd be worth refining each OSes section, or adding a dedicated "Debug Tools" section to Wiki recommending to get openocd from here.

**Comment by nvmker** [comment]
I updated Wiki page with instructions how to build OpenOCD with Homebrew from git:
https://github.com/electro-smith/DaisyWiki/wiki/1b.-Installing-the-Toolchain-on-Mac/5f2ded870f0e1897a8377c530a10cab7735a940a

**Comment by nvmker** [comment]
I also updated installation of gcc-arm-embedded to more convenient version, it can be added as exception for security checks without disabling/re-enabling security checks for each build:
https://github.com/electro-smith/DaisyWiki/wiki/1b.-Installing-the-Toolchain-on-Mac/4469417e597224f8968f277f6d3376790ee9ec91

**Comment by nvmker** [comment]
OpenOCD 0.11 released: http://openocd.org/2021/03/openocd-0-11-0-released
I updated Mac version of installation guide.
