### ISSUE TITLE
Better documentation on toolchain requested  

### ISSUE THREAD

**Issue by directgumby** [electro-smith/DaisyWiki#17]
Hi,

I am loking at your toolchain install instructions and there are two areas that could use a little more info:

1) Where you ask people to setup the environment variables:
  a) CYWGIN - what should the env variable be? (I assume cywgin but it is not clear from the docs)
  b) GNU tools - if I missed checking the box, what should the evn variable be?
  c) dfu-util - what should the env variable be? (I assume dfu-util, but it is not clear from the docs) 

2) How do I unpact the dfu-util 
  When I go to the link it shows a <stuff>.tar.xz?
  I have not been on a Linux system for some time, I've been coding Windows for a while, how do I unpack a tar.xz file?

**Comment by stephenhensley** [comment]
Hi, sorry for any confusion.

Re. 1: All three of the paths to the bin/ files should be added to the `PATH` variable in windows. That variable is filled with a list of directories. For example, the entries for my dfu-util and ARM Toolchain are:

![image](https://user-images.githubusercontent.com/9341384/112018852-29046180-8aec-11eb-973b-8848bbbf0a6c.png)

2. To unpack the dfu-util archive you can use an archive utility program like [Win-Rar](https://www.win-rar.com/start.html?&L=0) or [7-Zip](https://www.7-zip.org/)

I'll leave this issue open until we add these details to the appropriate locations within the wiki.

**Comment by directgumby** [comment]
Hi, My Daisy Filed arrived, and DFU still isn't working for me. 
I am wondering, what should the DFU path name be? DFU or DFU-UTIL?

**Comment by andrewikenberry** [comment]
We rewrote our [getting started guide](https://github.com/electro-smith/DaisyWiki/wiki/1.-Setting-Up-Your-Development-Environment).

This should help clear up any confusion on installing the toolchain.

If you're still having trouble, please reach out via the slack or daisy forum.
