### ISSUE TITLE
Document does not discuss if new Edge Browser (that is Chrome based) will work

### ISSUE THREAD

**Issue by directgumby** [electro-smith/DaisyWiki#18]
Hi,

Given I use Windows and the latest Edge browser that is Chrome based, I was wondering if Edge will work with your system?  It would be cool if it did.

Any info here would be appreciated.

**Comment by stephenhensley** [comment]
Hi, I just tested this, and it does work in Edge. 

Tested on version:
`Version 89.0.774.57 (Official build) (64-bit)`
