### ISSUE TITLE
csv pinout off by 1?

### ISSUE THREAD

**Issue by x37v** [electro-smith/DaisyWiki#19]
https://github.com/electro-smith/DaisyWiki/blob/master/resources/Daisy_Seed_Pinout.csv
vs
https://github.com/electro-smith/DaisyWiki/wiki/2.-Daisy-Seed-Pinout

The column for daisy pin number starts with 1 but the graphic starts from 0.

**Comment by stephenhensley** [comment]
The "Daisy Pin Number" corresponds to the physical pin number (small black number next to the photo of the seed in the graphical version).

The equivalent to the blue-box number is the `Arduino D#` column. That number is what is used if you want to get the `dsy_gpio_pin` value from the `DaisySeed::GetPin()` function, or to control the pin in Arduino.

**Comment by x37v** [comment]
ahh okay! i guess the graphic says `libdaisy pin` not `daisy pin`

sorry for the noise
