### ISSUE TITLE
No ./rebuild_libs.sh

### ISSUE THREAD

**Issue by reverbrick** [electro-smith/DaisyWiki#2]
Hey, I still wait for my board, but was happy to know that the lib is finally there. It still fails as there's no ./rebuild_libs.sh
Also when building examples I get the following:
PluckEcho.cpp:2:10: fatal error: daisysp.h: No such file or directory
    2 | #include "daisysp.h"
      |          ^~~~~~~~~~~
compilation terminated.

For each....

**Comment by stephenhensley** [comment]
oops! I had just split `rebuild_libs.sh` from `rebuild_all.sh` and forgot to merge the PR.

The file is there now.
