### ISSUE TITLE
pin b11, codec reset pin, on csv/xls

### ISSUE THREAD

**Issue by x37v** [electro-smith/DaisyWiki#21]
libDaisy shows [codec_reset_pin = {DSY_GPIOB, 11};](https://github.com/electro-smith/libDaisy/blob/fb2173eee60b9c5a594fbbd9911b0536c08a3610/src/daisy_seed.cpp#L263)

Could be nice to add this to the spreadsheet docs.

added PR for CSV https://github.com/electro-smith/DaisyWiki/pull/20

**Comment by stephenhensley** [comment]
fixed in PR
