### ISSUE TITLE
Will the new tool chain clean up the older install (pre all one install)?

### ISSUE THREAD

**Issue by directgumby** [electro-smith/DaisyWiki#25]
Hello,

I am trying to update my toolchain and I wanted to check as I had the older toolchain install and it is working, but will the two work together well?  Moreover, will it clean up the old toolchain when this installs?

Thanks,
Brett

**Comment by stephenhensley** [comment]
Depending on your OS it will be slightly different:

On Mac OS:

The toolchain install uses homebrew. So if the tools were previously installed then it won't change anything, and everything should continue to work as expected.

On Windows:

The install script only adds the new toolchain directory to the PATH variable, it does not delete the old entries. You can inspect this from the windows menu by typing "edit environment variables", and manually remove the old tools.

Typically, you should be able to see which tool you're using by invoking the `which` command, and it will echo the path to that program, which the new toolchain has within the DaisyToolchain/ hierarchy (i.e. `which make`)

---

We are planning to improve the process further, and have plans in the next month or two to iron out the installer further by creating a typical OS-specific installation package (along with an uninstaller) to make intalling/upgrading easier in the future.

Hope that answers your question! 😄

**Comment by stephenhensley** [comment]
The question has been addressed, and we'll be releasing an actual GUI installer for Windows in the next few that will remove this ambiguity.
