### ISSUE TITLE
Oopsy zip download uses incorrect link

### ISSUE THREAD

**Issue by CorvusPrudens** [electro-smith/DaisyWiki#29]
On the [Oopsy getting started page](https://github.com/electro-smith/DaisyWiki/wiki/1e.-Getting-Started-With-Oopsy-(Gen~-Integration)), the link used for downloading the Oopsy zip `https://github.com/electro-smith/oopsy/releases/latest/download/oopsy.zip` results in a "Not Found" error. 

The reason is that the actual zip isn't named `oopsy.zip`. It also has the versioning in the name, so just using the `latest` URL isn't sufficient to automatically track the latest release. Probably just a link to the latest release page is the way to go.

**Comment by CorvusPrudens** [comment]
Yes, it works without any extra steps (or at least, there's no `-ldaisy` errors). It compiled and uploaded to the patch just fine.

**Comment by stephenhensley** [comment]
this is resolved because the latest releases all have `oopsy.zip` files to download.
