### ISSUE TITLE
Add photo showing how to line up debugger with Patch SM

### ISSUE THREAD

**Issue by andrewikenberry** [electro-smith/DaisyWiki#35]

**Comment by as-def** [comment]
I am probably going to get a debugger soon... If so, I will try to attach an image of the connection with my patch.init(), if that helps, too?

**Comment by as-def** [comment]
wait, i just found this:

https://forum.electro-smith.com/t/patch-init-and-stlinkv3/3222/9 - you could link that :)

**Comment by takumi-ogata** [comment]
A photo of the debugger lining up with Patch SM has been added.

https://github.com/electro-smith/DaisyWiki/wiki/1.-Setting-Up-Your-Development-Environment#4b-flashing-the-daisy-via-debug-probe
