### ISSUE TITLE
Mac builds of pd2dsy are missing executable applications

### ISSUE THREAD

**Issue by Harry-Harrison** [electro-smith/DaisyWiki#37]
I feel like the title says it all, but neither of the Mac builds of pd2dsy have an executable application in. The Apple Silicon versions dont contain the file at all, whereas the intel version does contain a file, but it's a shortcut that is not runnable.

**Comment by stephenhensley** [comment]
This may be the case for all OSes at the moment.

You can run it by opening the internal `pd2dsyGUI/data/` folder, and running the executable `pd2dsy_gui`.

We're discussing solutions to this to make it a bit more user-friendly.

**Comment by takumi-ogata** [comment]
For Silicon (M1/M2), the`pd2dsy_gui` executable that's in the `pd2dsy_gui` folder is what you would need to open.
