### ISSUE TITLE
Windows 10: Cannot open DFU device 0483:df11

### ISSUE THREAD

**Issue by monkeyharhar** [electro-smith/DaisyWiki#4]
I'm in the process of trying to flash the Daisy with the Blink example. I've got the Daisy in DFU mode but dfu-util cannot access the device. It also cannot open the device when trying to list the devices using just dfu-util.

If I reset the Daisy out of DFU mode, it simply states that "No DFU capable USB device available". Are there some Windows 10 drivers that I need in order for this to work?

EDIT: Under Bluetooth & other devices, the Daisy shows up as "DFU in FS Mode" when entering DFU mode.

**Output:**
monke@FOLDINGTREE /cygdrive/c/users/monke/desktop/daisy/DaisyExamples/seed/blink
$ make program-dfu
dfu-util -a 0 -s 0x08000000:leave -D build/Blink.bin
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Invalid DFU suffix signature
A valid DFU suffix will be required in a future dfu-util release!!!
Cannot open DFU device 0483:df11
No DFU capable USB device available
make: *** [../../libdaisy/core/Makefile:235: program-dfu] Error 74

**Comment by andrewikenberry** [comment]
It looks like you need to update your USB driver. 

You can use Zadig for this. 
https://zadig.akeo.ie/

Launch zadig
Click options->list all devices
select DFU in FS Mode in the drop down (after putting the Daisy in DFU mode)
in the target driver box, select WinUSB.
Click replace driver

Let me know how that goes. 
I'll get the wiki updated ASAP.

**Comment by monkeyharhar** [comment]
Awesome! That worked perfectly.

The Blink example was successfully flashed to the Daisy.

**Comment by andrewikenberry** [comment]
Glad to hear it!
