### ISSUE TITLE
daisy seed json file and other things missing from the oopsy examples for max msp gen

### ISSUE THREAD

**Issue by androvisuals** [electro-smith/DaisyWiki#40]
As a complete beginner I was following this [tutorial](https://www.youtube.com/watch?v=HTXhd8sdxp4) and discovered that there is no json file or preset to export a simple gen patch to the daisy seed.
In my case I have a single sine wave which goes to outputs 1 and 2, after trying all the available modes like field, pedal, pod I didn't get anything to work.

Is there something that I'm missing on the wiki or anywhere else on how to get sound out of the daisy seed from an exported gen patch?

**Comment by takumi-ogata** [comment]
Hi androvisuals, 

Thank you for bringing this up. I just added "For the Daisy Seed, you can arbitrary select `Pod` if you're just using the audio I/O pins." in the tutorial.
