### ISSUE TITLE
the 'Zadig wiki page' link points to the DaisyWiki page itself

### ISSUE THREAD

**Issue by LubkoReminetskyy** [electro-smith/DaisyWiki#41]
When clicking on the 'Zadig wiki page' link - it passes to the same DaisyWiki home page.
Therefore I'm unable to get the information about updating the USB driver.
My Daisy is not visible as "DFU in FS Mode" in the web programmer.

**Comment by takumi-ogata** [comment]
Hi Lubomyr, 

I'm really sorry for the delay in response.
I recently fixed the link issue. Thank you for your patience.
