### ISSUE TITLE
Daisy Pinout PNG Audio pins do not match Pinout Sheet

### ISSUE THREAD

**Issue by monkeyharhar** [electro-smith/DaisyWiki#5]
In the pinout sheets, it states that pin 20 is AGND and that the audio in/out pins are 16-19. The PNG shows the audio in/out pins are 17-20. 

**From the sheets:**
16 | AUDIO IN L
17 | AUDIO INR
18 | AUDIO OUT L
19 | AUDIO OUT R
20 | AGND

**Comment by stephenhensley** [comment]
Thanks for letting us know! The PNG was the penultimate revision of the hardware, we'll upload the current production version of the PNG ASAP, and close this when we do.

**Comment by andrewikenberry** [comment]
This is fixed.
