### ISSUE TITLE
Hardware Documentation

### ISSUE THREAD

**Issue by Andrew-Hanlon** [electro-smith/DaisyWiki#7]
I received my Daisy Seed boards today and am excited to dive-in. However, I am not finding an obvious source for hardware documentation. For example what are the IO pins' current sourcing and sink capacities? 

Are there plans to build-up the hardware documentation?

Are there plans to build a getting started guide from the hardware development standpoint and not just the software side?

Thank you.

**Comment by stephenhensley** [comment]
@Andrew-Hanlon Yes, we are going to be building up just as much hardware documentation as we have provided for the software side of things.

The first bit of this will be going up very shortly (including a very basic 'datasheet' for the Daisy as well as the schematics for the Daisy, and the Daisy Patch breakout).

We'll be adding the other breakout board schematics, getting started guides, and many more hardware resources as well as fleshing out the details within the datasheet/user manuals from there.

**Comment by andrewikenberry** [comment]
The hardware repo is live: https://github.com/electro-smith/Hardware

**Comment by Andrew-Hanlon** [comment]
Thank you kindly!
