### ISSUE TITLE
Getting started Arduino: note to copy DaisySP lib into libraries folder

### ISSUE THREAD

**Issue by makingsoundmachines** [electro-smith/DaisyWiki#8]
Hey everyone, regarding the instructions on this page -
https://github.com/electro-smith/DaisyWiki/wiki/1a.-Getting-Started-(Arduino-Edition)

There should be some kind of hint that if you install **ArduinoDaisySP** ( https://github.com/electro-smith/ArduinoDaisySP ) to the IDE via .zip file, you need to manually add the files from **DaisySP** ( https://github.com/electro-smith/DaisySP ) without the example folder to the arduino library's location i.e. **Documents\Arduino\libraries\ArduinoDaisySP\src\utility\DaisySP**

It's easy to troubleshoot but if you don't do it (using the .zip install method) you get an error during compilation that daisysp.h is missing.

**Comment by andrewikenberry** [comment]
Thanks for bringing this up. I'm jumping on a fix today!

We'll probably change the install guide to avoid Git altogether for simplicity.

**Comment by makingsoundmachines** [comment]
@andrewikenberry this issue is solved with [the new Arduino integration](https://github.com/electro-smith/DaisyWiki/wiki/1a.-Getting-Started-(Arduino-Edition))
